name: flut_base_app_duck_drinks_with_flavors
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flut_micro_app_home:
    path: '../flut_micro_app_home'
  flut_micro_app_product:
    path: '../flut_micro_app_product'

dependency_overrides:
  flut_micro_commons_dependencies:
    path: '../flut_micro_commons_dependencies'
  flut_micro_commons_shared:
    path: '../flut_micro_commons_shared'
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.0
  mobx_codegen: ^2.0.4
  modular_test: ^2.0.0
  modular_codegen: ^3.0.3
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  assets:
    - packages/flut_micro_app_home/assets/lang/
    - .env_qa
    - .env_prd
    - .env_dev

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Duck Drinks Dev"
      android:
        applicationId: "br.com.jheimesilveira.duck_drinks.client.dev"
      ios:
        bundleId: "br.com.jheimesilveira.duck_drinks.client.dev"
    qa:
      app:
        name: "Duck Drinks QA"
      android:
        applicationId: "br.com.jheimesilveira.duck_drinks.client.qa"
      ios:
        bundleId: "br.com.jheimesilveira.duck_drinks.client.qa"

    prd:
      app:
        name: "Duck Drinks"
      android:
        applicationId: "br.com.jheimesilveira.duck_drinks.client"
      ios:
        bundleId: "br.com.jheimesilveira.duck_drinks.client"