name: flut_micro_commons_http_client
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flut_micro_commons_dependencies:
    path: '../flut_micro_commons_dependencies'
  flut_micro_commons_shared:
    path: '../flut_micro_commons_shared'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  modular_test: ^2.0.0

flutter: