name: flut_micro_commons_dependencies
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  unicons: ^2.1.0
  dio: ^4.0.6
  mobx: ^2.0.7+5
  floor: ^1.3.0
  package_info_plus: ^1.4.3+1
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  localization: ^2.1.0
  supercharged: ^2.1.1
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  flutter_mobx: ^2.0.6+1
  mask_text_input_formatter: ^2.4.0
  dartz: ^0.10.1
  asuka: ^2.0.0+1
  flutter_svg: ^1.1.4
  intl: ^0.17.0
  timer_count_down: ^2.2.1
  carousel_slider: ^4.1.1
  insta_like_button: ^0.1.1
  like_button: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  flutter_dotenv: ^5.0.2
  
dev_dependencies:
  build_runner: ^2.1.7
  modular_codegen: ^3.0.4
  modular_test: ^2.0.0
  floor_generator: ^1.2.0

  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  
flutter:


